package com.xinwei.java.leetcode.hashTable;

import java.util.HashMap;

/**
 * Created by xinweiwang on 4/26/17.
 */

/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */
public class Find_the_Difference {

    public char findTheDifference(String s, String t) {
    /*
        HashMap<Character,Integer> map = new HashMap<>();

        for(char c : t.toCharArray()){
            map.put(c,map.getOrDefault(c,0)+1);
        }

        for(char c: s.toCharArray()){
            if(map.get(c)==1) map.remove(c);
            else map.put(c,map.get(c)-1);
        }

        char res = 's';
        for(char c : map.keySet()){
            res =c;
        }
        return res;
        */
        char c = t.charAt(t.length()-1);

        for(int i=0;i<s.length();i++){
            c+=t.charAt(i);
            c-=s.charAt(i);
        }

        return c;

    }

}
